### ISSUE TITLE
About PhenoCam_bartlett2009.R

### ISSUE THREAD

**Issue by WuhuPilot11** [eco-hydro/phenofit-scripts#1]
Hello professor @kongdd , may I ask why such an error occurs when running the **_PhenoCam_bartlett2009.R_** (I use the ‘**_bartlett2009.filtered.rda_**’ data set)
Three libraries have been installed and it still shows that the function cannot be found
Thank you very much!
![image](https://user-images.githubusercontent.com/95268900/169338323-8d19cd6c-fee9-4efd-a479-3e7032f531d5.png)

**Comment by kongdd** [comment]
```R
library(phenofit) # the github version
library(zoo)
```

**Comment by WuhuPilot11** [comment]
Got the image, thanks for your guide!
