### ISSUE TITLE
Henan_pheno_to_tiff.Rmd issues in tidy data

### ISSUE THREAD

**Issue by AbidSarwar** [eco-hydro/phenofit-scripts#10]
Delete these instructions once you have read them.

---

Brief description of the problem
Henan_pheno_to_tiff.Rmd issues in tidy data
```r
# insert reprex here
```
![image](https://user-images.githubusercontent.com/89247564/225579585-516ce7de-17f1-461c-aa70-c94079ddbbc0.png)

```r
sessionInfo() # your sessionInfo, which version of phenofit are you using?
```

**Comment by AbidSarwar** [comment]
I think the version of phenofit is phenofit_V0.3.5 
this is the file I am using
![image](https://user-images.githubusercontent.com/89247564/225590957-08202053-16fb-4c59-acd5-0b2b567d21d8.png)

**Comment by kongdd** [comment]
Please do not paste picture. It is hard for me to reoccur this issue.
You should be aware that the latest version of phenofit is v0.3.8.

**Comment by kongdd** [comment]
This is why previous version not work now: https://github.com/eco-hydro/phenofit/pull/14

**Comment by AbidSarwar** [comment]
thank you Dear this help a lot, much appreciated your efforts and support.

**Comment by AbidSarwar** [comment]
https://drive.google.com/file/d/1NQBW0pfD-Yx__Ma20iSN4CcacwdiYWYs/view?usp=share_link

Dear Kong,

I have tried the latest version even though the problem is there. Can you please have a look at the files I am using ? I’ll be very thankful to your expert comments and time. I’m using above mentioned files with the latest Phenofit version 0.3.8

Abid
***@***.***
