### ISSUE TITLE
could not find function "select_first_nGS"

### ISSUE THREAD

**Issue by Rimagination** [eco-hydro/phenofit-scripts#11]
> df2 = select_first_nGS(df, nGS = 3)

##Error in select_first_nGS(df, nGS = 3) : 
## could not find function "select_first_nGS"

**Comment by kongdd** [comment]
source("main_pkgs.R") first
https://github.com/eco-hydro/phenofit-scripts/blob/de67875c20088b2d155c946428210f3527d60d2e/main_pkgs.R#L112

A complete example: <https://github.com/eco-hydro/phenofit-scripts/blob/master/multiGS_MODIS_Henan/phenofit-MOD13A2_HeNan.Rmd#L17>
