### ISSUE TITLE
 could not find function "as_SpatialPixelsDataFrame"

### ISSUE THREAD

**Issue by Rimagination** [eco-hydro/phenofit-scripts#12]
source("main_pkgs.R")
poly <- vect("data-raw/shp/poly_Henan.shp")

files <- dir(outdir, "*.tif", full.names = TRUE)

lst = map(files[1:3], ~ !is.na(sum(rast(.x)[[1:2]])) )
r_nGS = do.call(c, lst) %>% sum()
grid_nGS = as_SpatialPixelsDataFrame(raster::brick(r_nGS))

write_fig({
    plot(mask(r_nGS, poly))
}, "Figures/Figure_S4_Henan_growing_season_numbers.svg", 7, 5)

**Error in as_SpatialPixelsDataFrame(raster::brick(r_nGS)) : 
  could not find function "as_SpatialPixelsDataFrame"**

**Comment by kongdd** [comment]
It can be found at here.

```r
library(sp)

#' @export 
as_SpatialGridDataFrame <- function(x) {
    as(x, "SpatialGridDataFrame")
}
```
https://github.com/rpkgs/sf2/blob/1ea08826521bf8d9d57b97a784c76bbc796387ce/R/sp/as.R#L17-L19

**Comment by kongdd** [comment]
As the `sp` package is deprecated, you can use terra directly to plot.
