### ISSUE TITLE
Pixel-based implementation of the package

### ISSUE THREAD

**Issue by ymutua** [eco-hydro/phenofit-scripts#14]
Could you please provide a pixel-based example implementation of the package? The example given here is for one site pixel http://phenofit.top/articles/phenofit_CA-NS6.html

**Comment by kongdd** [comment]
You can find a spatial application case at here: <https://github.com/eco-hydro/phenofit-scripts/tree/master/WIP>. MODIS EVI In one agricultural province of China.

**Comment by ymutua** [comment]
Did you prepare the data elsewhere? I am just wondering where the data you load on line 4-6 of https://github.com/eco-hydro/phenofit-scripts/blob/master/multiGS_MODIS_Henan/s1_process_tiff.R come from

**Comment by kongdd** [comment]
Please read the readme file first. 
Two options: 
1. Download the Henan data from the Baidu Cloud;
![image](https://github.com/eco-hydro/phenofit-scripts/assets/9815742/d0f96466-ab8c-42bc-8220-1cbb110228d8)

2. Download from the GEE scripts, <https://code.earthengine.google.com/350aed10705fd98056a4b8c355a1a825>
