### ISSUE TITLE
GEE全国范围植被指数下载

### ISSUE THREAD

**Issue by sseeaann1234** [eco-hydro/phenofit-scripts#16]
https://code.earthengine.google.com/350aed10705fd98056a4b8c355a1a825

如何修改为全国范围？

**Comment by kongdd** [comment]
```js
var range = [xmin, ymin, xmax, ymax];
```
将代码中的range修改为中国范围，同时注销掉`img.clip(poly_NC);`。

https://code.earthengine.google.com/ae75b78dc229363e1036154ea19d09ba

**Comment by sseeaann1234** [comment]
还有一个问题，孔老师，我把全国的下载了，在使用并行运算的https://github.com/eco-hydro/phenofit-scripts/blob/master/WIP/s2_phenofit-MOD13A2_HeNan.Rmd时候出错了。clusterExport(cl, c("data", "LCs", "n", "list_options"))就是这一步，出错信息为“Error in serialize(data, node$con) : 链结书写发生了错误”。
