### ISSUE TITLE
Phenofit's get_pheno() plots deviate from curve parametrization 

### ISSUE THREAD

**Issue by MichiZehnder** [eco-hydro/phenofit-scripts#17]
Hi!

I have data on vegetation height for several years. I want to use `get_pheno()` (using an Elmore function) to extract the start of season in every year. I am not very much interested in senescence. My data only allows to work with phenological dates at the beginning of the season. 

Phenofit's `curvefit()` and `get_pheno(..., isPlot=TRUE)` plots nicely fitted curves on my input data. My issues is that if I parametrize the growth curves myself in ggplot using the Elmore function with the parameters from `get_param()`, I do not get the same curves as in the "autoplot" output of `get_pheno(..., isPlot=TRUE)`. In fact, some `mx` values derived from `get_params()` are clearly too high (indeed higher than the fine-fitted curves in `get_pheno(..., isPlot=TRUE)`) and the manually parametrized curves overshoot the input data points. Since the phenological dates of interest (start of season) is also part of the parametrization of the curve, this date is not correct and does not align with the input data. At the same time, the autoplot function `get_pheno(..., isPlot=TRUE)` (from which the curve parametrization is derived!) fits the curves smoothly to the input data points. So now, I am unsure if the phenological dates from `get_pheno()` are correct and my elmore parametrization is wrong? And I am wondering how exactly the curves in `get_pheno(..., isPlot=TRUE)` are generated if not by the elmore function that I use?
  
Here is, what I do:
  
load libraries: 

```{r, warning = FALSE, message= FALSE}
library(tidyverse)
library(lubridate)
library(data.table)
library(phenofit)
library(Ipaper)
library(kableExtra) 
```

Here the link to the sample data:
[sample_data](https://raw.githubusercontent.com/MichiZehnder/sample_data_phenofit/master/sample_dat.rds)

First, I define phenofit parameters and thresholds. I don't think that there is anything, which is cleary wrong here?

```{r, echo = TRUE}
nptperyear      <- 365              # 365, number of points per year
wmin            <- 0.01             # 0.01, the minimum weight of bad points 
rtrough_max     <- 0.02             # 0.02, highest possible value for local minima
ypeak_min       <- 3                # 3cm, min growth that the peak is still recognized
MaxPeaksPerYear <- 1                # 1, how many peaks per year should be found? Only one
maxExtendMonth <- 1                 # 1, Search good or marginal good values in previous and subsequent maxExtendMonth period.
minExtendMonth <- 0.5               # 0.5, Extend period defined by nextend and maxExtendMonth
minPercValid   <- 0                 # 0
wFUN           <- "wBisquare"       # "wBisquare",  bisquare is the most robust!
rFUN           <- "smooth_wWHIT"    # "smooth_wWHIT", rough curve fitting function
methods_fine   <- "Elmore"          # "Elmore" - function


TRS <- c(0.1, 0.2, 0.5)
```

I continue with pre-processing: growing season division:

```{r echo=TRUE}
### PREPROCESSING
INPUT <- check_input(t = subsample$date,           # Date variable
                     y = subsample$HS_plants,      # vegetation index
                     nptperyear = nptperyear,      # points per year (365)
                     wmin = wmin)                  # the minimum weight of bad points 

### GROWING SEASON DIVISION
brks <- season_mov(INPUT,
                   list(
                     rFUN = rFUN, 
                     wFUN = wFUN,
                     maxExtendMonth = maxExtendMonth,
                     wmin = wmin,
                     rtrough_max = rtrough_max, 
                     ypeak_min = ypeak_min,     
                     MaxPeaksPerYear = MaxPeaksPerYear))

```

here, the season division plot:

```{r echo=TRUE}
plot_season(INPUT, brks,
            ylab = "Plant Height",
            title = paste0(distinct(subsample, station_id), " Season"),
            show.legend = T) 

```

And here the fine curve fitting:
```{r echo = TRUE}
fit <- curvefits(INPUT, brks,
                 list(
                   methods = "Elmore", 
                   wFUN = wFUN,
                   iters = 2,
                   wmin = wmin,
                   nextend = 2,
                   maxExtendMonth = maxExtendMonth, 
                   minExtendMonth = minExtendMonth,
                   minPercValid = minPercValid
                 ))
```

I extract the parameters: 

```{r}

### getting phenological parameters:
pheno_param <- get_pheno(fit, TRS= TRS, method = "Elmore", IsPlot = T)

# getting elmore curve parameters:
elm_param <- get_param(fit)
```
![image](https://github.com/eco-hydro/phenofit-scripts/assets/98975794/800d0ea4-5ce2-4609-8ade-f9df4b22b775)

Note also, that the `mx` parameter from `get_param(fit)` are higher than the output above generated by `get_pheno()`.

Then, I merge all the parameters into one tibble.

```{r}
all_params <- pheno_param$doy %>% 
  melt_list("meth") %>%  
  mutate(station_id = unique(subsample$station_id),
         year = lubridate::year(origin)) %>% 
  left_join(elm_param$Elmore, by = "flag") %>% 
  left_join(gof_param, by = c("flag", "meth"))
```

### Curve fitting myself
Then, I do the curve fitting myself using the elmore function as defined below. 

```{r}
# define Elmore function
elm_fun <- function(t, mn, mx, sos, rsp, eos, rau, m7) {
  mn + (mx - m7 * t) * (1/(1 + exp(-rsp * (t - sos))) - 1/(1 + exp(-rau * (t - eos))))
}

```
I believe that here could be a source of error. However, according to the package documentation, this is the same parametrization as used in the fine-fitting in `get_pheno(..., isPlot=TRUE)`. I use `DER.sos` and `DER.eos` from `get_pheno()` as inputs for `sos` and `eos`. Is this correct or could this be the problem? The other curve parameters are named the same in the `get_param()` output.

I merge the input data with the phenological parameters and create a plot. I use `mutate(phenofit = elm_fun(..))` to reproduce the phenofit curve in `ggplot()`.

```{r, warning = FALSE}
subsample  %>%
  left_join(all_params, by = c('year', 'station_id')) %>% 
  mutate(phenofit = elm_fun(doy, mn, mx, DER.sos, rsp, DER.eos, rau, m7)) %>% # here I generate the y values based on the parameters
  ggplot(.)+
  geom_point(aes(y = HS_plants, x = doy), size = 0.5) + 
  geom_path(aes(x = doy, y = phenofit, colour = "Phenofit"), size = 1)+
  geom_point(aes(y = HS_plants, x = doy, colour = "Plant signal"), size = 1) + 
  geom_vline(aes(xintercept = DER.sos, color = "SOS"))+
  xlim(100, 340) + 
  ylim (0, 80) +
  labs( y = "Plant Height [cm] ", x = "DOY") + 
  scale_color_manual(name = element_blank(), values = c("Plant signal" = "darkgreen", "Phenofit"  = "darkred")+
  facet_wrap(~year, ncol = 1)
```

![image](https://github.com/eco-hydro/phenofit-scripts/assets/98975794/54f42001-d9aa-4873-afac-10b075dde6c4)

And comparing this with the `get_pheno()` output, we can see that the curves are different from phenofit's curves! And most importantly, the points for the start of season (derivative method) are also not matching the input points.  
```{r, results = 'hide'}
### compare with get_pheno()
get_pheno(fit, TRS= TRS, method = "Elmore", IsPlot = T)

```

So my question is: **Can someone explain to me why there is this deviation between `get_pheno(isPlot=TRUE)` and the curves when parametrized by the elmore parameters? Or asked in another way: how are the curves in `getpheno(isPlot=TRUE)` generated?** And how do I extract the `DER.sos` points from `getpheno(isPlot=TRUE)` as well as the growth curves generated by it?

here the link to the repository where I uploaded the whole code and sample data: [https://github.com/MichiZehnder/sample_data_phenofit.git](https://github.com/MichiZehnder/sample_data_phenofit.git)

Thank you for your help in advance!

cheers
Michael

```{r}
R version 4.2.1 (2022-06-23 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 22000)

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
 [1]  data.table_1.14.2 lubridate_1.9.3   forcats_1.0.0     stringr_1.5.0    
 [6] dplyr_1.1.2       purrr_1.0.1       readr_2.1.4       tidyr_1.3.0       tibble_3.2.1     
[11] ggplot2_3.4.1     tidyverse_2.0.0   phenofit_0.3.8   
 
```

**Comment by kongdd** [comment]
You can find the reason at: 

<https://github.com/eco-hydro/phenofit/blob/5c4d7f34f143832ff301ad37149e7cbd9e8a69c5/R/curvefits.R#L81>

```r
date.origin = as.Date("2000-01-01")
doys <- as.numeric(difftime(t, date.origin, units = "day")) # + 1
```

So `t` is not doy, `t` is how many days from "2000-01-01".
If you take the proper `t`, the curve should looks normal.

**Comment by kongdd** [comment]
It is welcome and appreciated if you cound post your revised version. 
Loop forward to the right result.

**Comment by kongdd** [comment]
Another option, you can get the fitting results from the following script:

```r
> get_fitting(fit)
[data.table]: 
# A data frame: 554 × 6
   flag   t              y meth   ziter1 ziter2
   <chr>  <date>     <dbl> <chr>   <dbl>  <dbl>
 1 2017_1 2017-05-21 0     Elmore  0.414      0
 2 2017_1 2017-05-22 0     Elmore  0.420      0
 3 2017_1 2017-05-23 0     Elmore  0.427      0
 4 2017_1 2017-05-24 0.454 Elmore  0.436      0
 5 2017_1 2017-05-25 0.975 Elmore  0.447      0
 6 2017_1 2017-05-26 0.473 Elmore  0.460      0
 7 2017_1 2017-05-27 0.879 Elmore  0.477      0
 8 2017_1 2017-05-28 0.404 Elmore  0.498      0
 9 2017_1 2017-05-29 0.481 Elmore  0.525      0
10 2017_1 2017-05-30 0.577 Elmore  0.558      0
```

Thanks for using our package.
