### ISSUE TITLE
Phenofit for Australian Vegetation using Sentinel-2 Image

### ISSUE THREAD

**Issue by UQ-Raja-Ram-Aryal** [eco-hydro/phenofit-scripts#18]
I use the Digital Earth Australia (DEA) sandbox environment to extract Vegetation Indices (EVI, NDVI). I filtered the data with a cloud cover of more than 90% and then used a median filter to remove some outliers. Again, after that, I applied Singular Spectrum Analysis(SSA) to my dataset and got the trend value from that. I want to derive phenological metrics using the Phenofit with those trend values. 

I  also have an SSA trend product of daily mean GPP of the exact VIs date from Flux Tower measurement. So, finally, I have data from 2015 to 2023 that is very irregular. In some years, I have even data less than 15 observations. I tried using the following code with my data, but I need help finding the output from all the years. Do you know how I can solve this problem ? 
All the data used and R code is attached herewith.
[TumbaRumba_Phenofit.zip](https://github.com/eco-hydro/phenofit-scripts/files/13724334/TumbaRumba_Phenofit.zip)

**Comment by UQ-Raja-Ram-Aryal** [comment]
[CalperumMallee_EVI.csv](https://github.com/eco-hydro/phenofit-scripts/files/13723988/CalperumMallee_EVI.csv)
[CalperumMallee_EVI2.csv](https://github.com/eco-hydro/phenofit-scripts/files/13723990/CalperumMallee_EVI2.csv)
[CalperumMallee_NDVI.csv](https://github.com/eco-hydro/phenofit-scripts/files/13723991/CalperumMallee_NDVI.csv)
[CalperumMallee_NIRv.csv](https://github.com/eco-hydro/phenofit-scripts/files/13723992/CalperumMallee_NIRv.csv)

**Comment by kongdd** [comment]
phenofit didn't perform well in your data. It seems that land cover changes after 2020. 
Issue might root in the growing season division.

phenofit may not suitable for your case.

**Comment by UQ-Raja-Ram-Aryal** [comment]
There are no land cover changes. There is no GPP data due to forest fire, so when fusing the sentinel-2 data with GPP data, there is an insufficient number of observations, but after 2020, there will be sufficient data for 2021 and 2022.

**Comment by UQ-Raja-Ram-Aryal** [comment]
## This is almost final code no error. error only in saving the data which will fixed this year: 2024/01/01
library(phenofit)
library(Ipaper) # remotes::install_github("rpkgs/Ipaper")
library(grid)
library(ggplot2)
library(ggnewscale)
library(lubridate)

# Supersites and Variables
supersites <- c('Tumbarumba') # 'AliceMulga', 'BoyaginWandoo', 'CalperumMallee', 'Cumberland', 'GinginBanksia', 'GreatWestern', 'Litchfield', 'RobsonCreek', 'Tumbarumba', 'Warra', 'Wombat')
variables <- c('NDVI') #'NDVI', 'EVI', 'EVI2', 'NIRv')

# Base directory
base_dir <- "C:/Users/uqrarya1/OneDrive - The University of Queensland/PHD_UQ/Data/Phenology/LSP_Metrics/Phenofit"
print(base_dir)

# Loop through each supersite and variable
for (site in supersites) {
  for (var in variables) {
    # Construct the file path for the current combination
    file_path <- paste0(base_dir, "/", "input_data/VIs/Merged_DEA_oa_fmask_SSA_Original_GPP/3Days/", site, "/", site, "_", var, "_Phenofit.csv")
    
    # Check if the file exists
    if (file.exists(file_path)) { 
      tryCatch({
        # Read the data
        phenofit_data <- read.csv(file_path)
        d <- phenofit_data
        summary(d)
        # Convert date column
        
        d$t <- as.Date(d$t)
        
        # Set parameters
        date_start <- '2016-01-01'
        date_end <- '2023-12-31'
        
        # Filter data based on date range
        
        if (!is.null(date_start) && !is.null(date_end)) {
          date_start <- as.Date(date_start)
          date_end <- as.Date(date_end)
          date_filter <- d$t >= date_start & d$t <= date_end
          d <- d[date_filter, ]
        }
        
        xlim <- c(date_start, date_end)
        print(paste("xlim:", xlim))
        print(d)
        summary(d)
        nptperyear <- 73
        wFUN <- "wTSM"
        # rFUN <- "smooth_wSG", "smooth_wWHIT", "smooth_wHANTS"
        wmin <- 0.2
        methods_fine <- c("AG", "Zhang", "Beck", "Elmore", "Gu")
        frame <- floor(nptperyear / 5) * 2 + 1
        print(frame)
        maxExtendMonth = 6
        nextend <- ceiling(maxExtendMonth/12*nptperyear)
        print(nextend)
       
        ## Check input 
        INPUT <- check_input(d$t, d$y, d$w, QC_flag = d$QC_flag,
                             nptperyear = nptperyear,
                             maxgap = nptperyear/4, wmin = 0.2, south = TRUE, verbose = TRUE)
        
        print(INPUT)
        print(str(INPUT))
        summary(INPUT)
        
 
        # curve fitting by year
        brks_mov <- season_mov(INPUT,
                               options = list(
                                 rFUN = "smooth_wWHIT", wFUN = "wTSM", maxExtendMonth = 6, calendarYear = TRUE, wmin = 0.2,
                                 lambda = NULL, iters = 2,
                                 r_min = 0.05, ypeak_min = 0.1,
                                 verbose = TRUE
                               ), years.run = 2016:2020
                               )
        
        warning()
        
        print(str(brks_mov))
        
        ## figure (Fig. 4)
        plot_season(INPUT, brks_mov, ylab = var, margin = 0.2, show.shade = FALSE)
        
        ## 2.4 Curve fitting
        fits <- curvefits(
          INPUT, brks_mov,
          options = list(
            methods = methods_fine,
            wFUN = wFUN,
            nextend = NULL, maxExtendMonth = 1, minExtendMonth = 0.5, minPercValid = 0.2
          )
        )
        
        # Display any warnings generated
        warnings()
        
        # Print the output of curvefits
        print(fits)
        
       
        ## 2.5 Extract phenology
        TRS = c(0.1, 0.2, 0.5)
        l_pheno <- get_pheno(fits, TRS = TRS, IsPlot = FALSE) #%>% map(~melt_list(., "meth"))
        pheno <- l_pheno$doy %>% melt_list("meth")
        
        print(l_pheno)
        print(pheno)
        warning()
        
        
        # Define the output directory
        output_dir <- paste0("Phenofit_Results/VIs/smooth_wWHIT/Merged_DEA_oa_fmask_SSA_Original_GPP/3Days/", site)
        full_output_dir <- file.path(base_dir, output_dir)
        
        # Create the directory if it does not exist
        if (!dir.exists(full_output_dir)) {
          dir.create(full_output_dir, recursive = TRUE)
        }
        
        # Define the full paths for the files to be saved
        file_path_pheno <- file.path(full_output_dir, paste0(site, "_", var, "_pheno.csv"))
        file_path_l_pheno <- file.path(full_output_dir, paste0(site, "_", var, "_l_pheno.csv"))
        
        # Save the datasets
        write.csv(pheno, file_path_pheno, row.names = FALSE)
        write.csv(l_pheno, file_path_l_pheno, row.names = FALSE)
        
      }, error = function(e) {
        cat("An error occurred with site", site, "and variable", var, ": ", e$message, "\n")
      })
    } else {
      cat("File not found: ", file_path, "\n")
    }
  }
}
warnings()   

I am using this final code for developing Sentinel-based LSP metrics and want to compare the results with three algorithms. wWHIT, wHANTS and wSG. Why am I getting the same results from all algorithms?

**Comment by kongdd** [comment]
Did you update rFUN for each method? 
You may need to check the curve fitting results of rough fitting.
<https://github.com/eco-hydro/phenofit/blob/5c4d7f34f143832ff301ad37149e7cbd9e8a69c5/R/roughFit.R>

**Comment by UQ-Raja-Ram-Aryal** [comment]
Yes I change, rFUN and also change lamda, nf and frame for different algorithm. I am working with evergreen species.

**Comment by kongdd** [comment]
In our MEE paper, we have documented that phenofit has limited ability to extract vegetation phenology from Sentinel. You may interest in the paper of Li2017. 

![image](https://github.com/eco-hydro/phenofit-scripts/assets/9815742/0c0ea2e8-7ba2-4c04-8d38-7cbb3d1a8ce2)

R is low efficient in computing. Julia is more promising <https://github.com/eco-hydro/phenofit.jl>.
If you have interest, we can move forward on translating phenofit.R to julia, and implementing new algorithms for Sentinel.

About your issue, I will have a try.

**Comment by kongdd** [comment]
could you post your data of https://github.com/eco-hydro/phenofit-scripts/issues/18#issuecomment-1901859356

**Comment by UQ-Raja-Ram-Aryal** [comment]
I am pleased to move to Julia. I am eager to work with you to develop a new algorithm using sentinel data.

> could you post your data of [#18 (comment)](https://github.com/eco-hydro/phenofit-scripts/issues/18#issuecomment-1901859356)

[Tumbarumba_EVI_Phenofit.csv](https://github.com/eco-hydro/phenofit-scripts/files/13997218/Tumbarumba_EVI_Phenofit.csv)
[Tumbarumba_EVI2_Phenofit.csv](https://github.com/eco-hydro/phenofit-scripts/files/13997219/Tumbarumba_EVI2_Phenofit.csv)
[Tumbarumba_NDVI_Phenofit.csv](https://github.com/eco-hydro/phenofit-scripts/files/13997220/Tumbarumba_NDVI_Phenofit.csv)
[Tumbarumba_NIRv_Phenofit.csv](https://github.com/eco-hydro/phenofit-scripts/files/13997221/Tumbarumba_NIRv_Phenofit.csv)

**Comment by UQ-Raja-Ram-Aryal** [comment]
I have GPP data from Flux on those sites. Altogether I am working on the 12 supersites of Australian vegetation.

**Comment by kongdd** [comment]
You can contribute to https://github.com/eco-hydro/VegCurveFit.jl, and https://github.com/eco-hydro/VegSeasons.jl. Pull requests are welcome.

**Comment by UQ-Raja-Ram-Aryal** [comment]
Hi Dongdong,

Thank you for managing this. Is it possible to make one file in which we can upload our original csv file, run different steps, and get the final phenometrics. Then I am able to customize the codes inside by doing different hit-trial approach.

**Comment by kongdd** [comment]
Your case is beyond the ability of `phenofit`. It involves uneven space rough fitting (the Equation of wSG and wWHIT should be rededuced, and rewrite).

As software development is a long-time work, and currently it is not my first priority. Hence, this issue will stop at here.

I suggest removing years with limited VI observations. If you have to keep this bad years, landcover cannot be changed.
