### ISSUE TITLE
About Missing Values in Time Series

### ISSUE THREAD

**Issue by WuhuPilot11** [eco-hydro/phenofit-scripts#2]
hello professor @kongdd :
The following is my code and picture, can I trouble you to see what is wrong:
I used the camera to get 255 photos per year. After calculating the GCC, I used your phenofit to fit, and found that the NA value of the missing date in the obtained picture was not reflected. It looks like the intervals for each point in the graph are continuous

`m <-read.table("C:/Users/Zhuan/Desktop/Timeseries/ZB_liriodendron_2021.csv", header=TRUE, sep=",")`

#转化成DOY，向上取整数，范围[1,365]
`t_pre = m$time %>% {difftime(.,  .[1], units = "day")} %>% as.numeric()`
`t <- ceiling(t_pre +1) `

#检查数据和平滑
`l <-check_input(t,m$gcc,,nptperyear = length(m$gcc),south = FALSE,maxgap = 5,
                date_start = 1, date_end = 365, mask_spike = TRUE, na.rm = TRUE)`

`y_wHANTS <- smooth_wHANTS(l$y, l$t, l$w, nf =8,ylu = l$ylu,periodlen = 365,
                          nptperyear = length(m$gcc), iters = 2)`
#From PhenoCam_bartlett2009.R
`r = curvefit(y_wHANTS[["zs"]][["ziter2"]], t)`
`par(mfrow = c(1, 5), mgp = c(3, 0.6, 0), mar = rep(0, 4), yaxt = "n", xaxt = "n")`
`r_pheno = get_pheno(r, method = "Beck", IsPlot = TRUE)`

The picture is this：
![Rplot03](https://user-images.githubusercontent.com/95268900/172847145-8346f999-b4c7-474b-abc6-f4ee1621c8d3.png)

Thank you very much!

**Comment by kongdd** [comment]
想要快速的解决bug，需要给我一个可以重复运行的例子，否则我也无能为力。
