### ISSUE TITLE
`users/kongdd/pkgs:pkgs.js` renamed

### ISSUE THREAD

**Issue by Steve-717** [eco-hydro/phenofit-scripts#20]
#issues about downloading the sentinel-2 EVI using GEE code provided

I would like to run the GEE code about downloading the sentinel-2 EVI, but it shows "Cannot find required script: users/kongdd/pkgs:legends.js"

**Comment by kongdd** [comment]
Show your GEE link. Download images do not require `legends.js`.

**Comment by Steve-717** [comment]
I directly clicking the example link and run the code, it doesn't work (But it worked last week). I think the issue exist in "var pkgs = require('users/kongdd/pkgs:pkgs.js')", there could be some changes about the path or the script. Thanks

**Comment by kongdd** [comment]
`var pkgs = require('users/kongdd/pkgs:pkgs')` works. rm the `.js` subfix.

**Comment by kongdd** [comment]
The bug of `pkgs.jl` is also fixed. `pkg` without `.js` is the next generation, which is blazing fast in loading time.
