### ISSUE TITLE
文件main_pkgs.R中plot_phenomap函数的定义

### ISSUE THREAD

**Issue by gxy129** [eco-hydro/phenofit-scripts#21]
孔老师您好！我正在学习R语言并复现河南省的phenofit代码，但是绘制物候这里发生了报错，这里的这个函数没有定义：
![11](https://github.com/eco-hydro/phenofit-scripts/assets/151372685/24164480-57dc-40d2-93c8-39acd9e68867)
![22](https://github.com/eco-hydro/phenofit-scripts/assets/151372685/6be7cb97-fc24-4982-ac0f-e05ee7e409ef)
想请教您怎么修改，谢谢老师！

**Comment by kongdd** [comment]
绘图函数可以跳过，用自己的方法绘图

**Comment by kongdd** [comment]
lattice绘图方式是被淘汰的方法，基于lattice的绘图函数很长时间没有维护了，你可以到这里找一找有没有对应的代码<https://github.com/rpkgs/lattice.layers>。

**Comment by gxy129** [comment]
好的老师，非常感谢！
