### ISSUE TITLE
No valid pixel in GEE Code to download data

### ISSUE THREAD

**Issue by MohammadJavadSoltani** [eco-hydro/phenofit-scripts#23]
I'm trying to use [GEE Code](https://code.earthengine.google.com/350aed10705fd98056a4b8c355a1a825) you provided thoughtfully for input data, but as I changed the ROI to another that I draw in GEE, I receive this error:

 `Error: No valid (un-masked) pixels in export region. (Error code: 3)`

It is worse to mention that my image collection has (**187 elements**) from '2015-01-01', '2023-12-31'. So there are  **no empty dataset** here.

As I don't have access to `var pkgs = require('users/kongdd/pkgs:pkgs.js');` I had no other way to solve the problem.

This is the [link to my code](https://code.earthengine.google.com/e7ce60d2ea41fe2ecd07971d5efcee9a):

Thanks for your invaluable Package and sorted documentation!

**Comment by kongdd** [comment]
You need to change `range` to your case. Double check `range` through the following script:
```js
var poly = ee.Geometry.Rectangle(range, 'EPSG:4326', false);
Map.addLayer(poly);
```

**Comment by MohammadJavadSoltani** [comment]
Thank you for your early and helpful answer.
I totally forgot about RANGE! I've downloaded my data successfully.
Best Regards!

**Comment by kongdd** [comment]
You are welcome.
