### ISSUE TITLE
could not find function "rast_coord"

### ISSUE THREAD

**Issue by hanhao20190402** [eco-hydro/phenofit-scripts#24]
source("G:\\P4\\phenofit-scripts-master\\phenofit-scripts-master\\multiGS_MODIS_Henan\\previous\\phenofit-MOD13A2_HeNan.R") 
错误于rast_coord(r[[1]]): 没有""这个函数

**Comment by kongdd** [comment]
It is at <https://github.com/rpkgs/sf2/blob/c5d8aa4d2efe5b20d378dc9e6c68273b71379bc0/R/tools_rast.R#L61>

**Comment by hanhao20190402** [comment]
Thanks for your prompt reply. It works fine when I modify the "rast_coord" to "rast_df“ ，and it still cant work with "rast_coord".
