### ISSUE TITLE
phenofit用户群

### ISSUE THREAD

**Issue by kongdd** [eco-hydro/phenofit-scripts#3]
如有问题，可在github提交issue。

**Comment by bobilong** [comment]
非常感谢孔老师的phenofit包！对估算热带物候给了我们很大启发和帮助，希望可以建个群交流讨论。

**Comment by YANQIN2021** [comment]
正在学习孔老师的phenofit包来提取物候参数，受益良多。

**Comment by Hisschao** [comment]
点赞数量达到了，期待建立phenofit的用户群 ，方便大家推广

**Comment by Hisschao** [comment]
> 若此条评论点赞超过10次，则建一个用户群为用户解答
老师 您好我看到点赞数量已经达到了 ，为了方便大家学习phenofit，想问下群号是多少？

**Comment by kongdd** [comment]
感谢大家对phenofit感兴趣。
但这段时间需要上课，抱歉！这学期晚些才能建phenofit用户群。

**Comment by kongdd** [comment]
如果使用遇到bug，请先在GitHub提交issue，我会尽快帮大家解决。
ps: 想要问题尽快解决，需要提交一个能够重现bug的脚本及相关数据。

**Comment by kongdd** [comment]
为河南物候提取示例，添加了更加详细的说明，有需要的朋友请自行翻阅。

- <https://github.com/eco-hydro/phenofit-scripts/blob/master/multiGS_MODIS_Henan/phenofit-MOD13A2_HeNan.md>
- <https://github.com/eco-hydro/phenofit-scripts/blob/master/multiGS_MODIS_Henan/Henan_pheno_to_tiff.md>

**Comment by Diyanfeng1998** [comment]
老师可以建了吗（期待）

**Comment by zhouxinrong** [comment]
> 非常感谢孔老师的phenofit包！对夏威夷物候给了我们很大的启发和帮助，希望可以建立个群交流讨论。

老师您好，我刚开始学习孔老师的phenofit包，有些问题不太理解，可以请教您吗？

**Comment by zhouxinrong** [comment]
> 感谢大家对 phenofit 感兴趣。 但是有一段时间需要上课，抱歉！这个学期晚一些才能建立 phenofit 用户群。

孔老师您好，咱们啥时候可以建群呀，真的很想和大家探讨有关phenofit包的学习问题呢，谢谢老师了。
