### ISSUE TITLE
running phenofit-MOD13A2_HeNan.R，运行打印都是NULL正常吗

### ISSUE THREAD

**Issue by liuh1995** [eco-hydro/phenofit-scripts#7]
谢谢孔老师！
还想请教一个问题，运行打印都是NuLL正常吗？
![image](https://user-images.githubusercontent.com/53523867/200209506-4926c047-101a-47c2-94be-b6873972524e.png)

我试着去linux系统并行计算，时间确实挺长的

**Comment by kongdd** [comment]
同一个问题，不要建多个issue。

**Comment by liuh1995** [comment]
> 同一个问题，不要建多个issue。Duplicated with #6 .

好的，谢谢，不影响是吧
